packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": 5.83.0
  "@trpc/client": 11.4.3
  "@trpc/server": ^11.4.3
  "@trpc/tanstack-react-query": 11.4.3
  "@types/node": ^24.0.14
  "@vitejs/plugin-react": ^4.7.0
  eslint: ^9.28.0
  hono: ^4.8.5
  prettier: ^3.6.2
  superjson: ^2.2.2
  tailwindcss: ^3.4.17
  typescript: ^5.8.3
  vite: ^5.1.4
  zod: ^3.24.1

catalogs:
  react19:
    "@types/react": ^19.1.6
    "@types/react-dom": ^19.1.5
    react: ^19.0.0
    react-dom: ^19.0.0

onlyBuiltDependencies:
  - esbuild
